import { store } from "../store.js";

interface DeployResult {
  branch: string;
  prUrl: string | null;
  commitSha: string | null;
}

export async function deployerAgent(runId: string): Promise<DeployResult> {
  const run = store.getRun(runId);
  if (!run) throw new Error(`Run ${runId} not found`);

  const token = process.env.GITHUB_TOKEN;
  const owner = process.env.GITHUB_OWNER;
  if (!token || !owner) {
    store.addLog(runId, {
      agent: "deployer",
      event: "progress",
      message: "No GITHUB_TOKEN or GITHUB_OWNER — skipping GitHub deployment",
    });
    return { branch: "qalibur/run-" + runId.slice(0, 8), prUrl: null, commitSha: null };
  }

  const repoMatch = run.repoUrl.match(/github\.com\/([^/]+)\/([^/]+)/);
  if (!repoMatch) {
    return { branch: "qalibur/run-" + runId.slice(0, 8), prUrl: null, commitSha: null };
  }

  const [, repoOwner, repoName] = repoMatch;
  const { Octokit } = await import("@octokit/rest");
  const octokit = new Octokit({ auth: token });
  const branch = `qalibur/run-${runId.slice(0, 8)}`;

  try {
    const { data: defaultBranch } = await octokit.rest.repos.get({
      owner: repoOwner,
      repo: repoName.replace(".git", ""),
    });
    const baseBranch = defaultBranch.default_branch;

    const { data: ref } = await octokit.rest.git.getRef({
      owner: repoOwner,
      repo: repoName.replace(".git", ""),
      ref: `heads/${baseBranch}`,
    });

    await octokit.rest.git.createRef({
      owner: repoOwner,
      repo: repoName.replace(".git", ""),
      ref: `refs/heads/${branch}`,
      sha: ref.object.sha,
    });

    const artifacts = run.artifacts.filter((a) =>
      ["feature-file", "playwright-script"].includes(a.type)
    );

    let treeSha = ref.object.sha;
    for (const artifact of artifacts) {
      const { data: blob } = await octokit.rest.git.createBlob({
        owner: repoOwner,
        repo: repoName.replace(".git", ""),
        content: Buffer.from(artifact.content).toString("base64"),
        encoding: "base64",
      });

      const path =
        artifact.type === "feature-file"
          ? `tests/features/${artifact.filename}`
          : `tests/e2e/${artifact.filename}`;

      const { data: tree } = await octokit.rest.git.createTree({
        owner: repoOwner,
        repo: repoName.replace(".git", ""),
        base_tree: treeSha,
        tree: [{ path, mode: "100644", type: "blob", sha: blob.sha }],
      });

      const { data: commit } = await octokit.rest.git.createCommit({
        owner: repoOwner,
        repo: repoName.replace(".git", ""),
        message: `[qalibur] Add ${artifact.filename}`,
        tree: tree.sha,
        parents: [treeSha],
      });

      treeSha = commit.sha;

      await octokit.rest.git.updateRef({
        owner: repoOwner,
        repo: repoName.replace(".git", ""),
        ref: `heads/${branch}`,
        sha: commit.sha,
      });
    }

    const { data: pr } = await octokit.rest.pulls.create({
      owner: repoOwner,
      repo: repoName.replace(".git", ""),
      title: `[Qalibur] Generated tests for: ${run.featureDescription.slice(0, 60)}`,
      body: `## Qalibur Automated QE Run\n\n**Feature:** ${run.featureDescription}\n\n**Artifacts generated:**\n${artifacts.map((a) => `- ${a.filename} (${a.type})`).join("\n")}\n\n---\n*Generated by [Qalibur](https://github.com/pragatig25/qalibur)*`,
      head: branch,
      base: baseBranch,
    });

    return { branch, prUrl: pr.html_url, commitSha: treeSha };
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    store.addLog(runId, {
      agent: "deployer",
      event: "error",
      message: `GitHub deployment error: ${message}`,
    });
    return { branch, prUrl: null, commitSha: null };
  }
}
