import { useState } from "react";

export function ArtifactViewer({ artifacts }) {
  const [activeIdx, setActiveIdx] = useState(0);

  if (!artifacts || artifacts.length === 0) {
    return <div className="card" style={{ color: "var(--text-muted)" }}>No artifacts yet</div>;
  }

  const active = artifacts[activeIdx];

  return (
    <div>
      <div className="artifact-tabs">
        {artifacts.map((a, i) => (
          <button
            key={a.id || i}
            className={`artifact-tab ${i === activeIdx ? "active" : ""}`}
            onClick={() => setActiveIdx(i)}
          >
            {a.filename}
          </button>
        ))}
      </div>
      <div style={{ fontSize: 12, color: "var(--text-muted)", marginBottom: 8 }}>
        {active.type} — generated by <strong>{active.agent}</strong>
      </div>
      <div className="artifact-content">{active.content}</div>
    </div>
  );
}
